### ISSUE TITLE
Compilation Error: No rule to make target 'arch/arm/boot/dts/broadcom/bcm2711-rpi-cm4.dtb'

### ISSUE THREAD

**Issue by avanc** [ccrisan/thingos#72]
After merging changes from dev branch, building Raspberry Pi 4 image fails:

    2021-05-25T17:09:08.7893348Z make[1]: Leaving directory '/home/runner/work/photOS/photOS/output/raspberrypi4/build/linux-custom'
    2021-05-25T17:09:08.7904897Z PATH="/home/runner/work/photOS/photOS/output/raspberrypi4/host/bin:/home/runner/work/photOS/photOS/output/raspberrypi4/host/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" PKG_CONFIG="/home/runner/work/photOS/photOS/output/raspberrypi4/host/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_LIBDIR="/home/runner/work/photOS/photOS/output/raspberrypi4/host/lib/pkgconfig:/home/runner/work/photOS/photOS/output/raspberrypi4/host/share/pkgconfig" BR_BINARIES_DIR=/home/runner/work/photOS/photOS/output/raspberrypi4/images KCFLAGS=-Wno-attribute-alias DTC_FLAGS=-@ /usr/bin/make -j3 HOSTCC="/home/runner/work/photOS/photOS/output/raspberrypi4/host/bin/ccache /usr/bin/gcc -O2 -I/home/runner/work/photOS/photOS/output/raspberrypi4/host/include -L/home/runner/work/photOS/photOS/output/raspberrypi4/host/lib -Wl,-rpath,/home/runner/work/photOS/photOS/output/raspberrypi4/host/lib" ARCH=arm INSTALL_MOD_PATH=/home/runner/work/photOS/photOS/output/raspberrypi4/target CROSS_COMPILE="/home/runner/work/photOS/photOS/output/raspberrypi4/host/bin/arm-none-linux-gnueabihf-" DEPMOD=/home/runner/work/photOS/photOS/output/raspberrypi4/host/sbin/depmod INSTALL_MOD_STRIP=1 -C /home/runner/work/photOS/photOS/output/raspberrypi4/build/linux-custom bcm2711-rpi-4-b.dtb broadcom/bcm2711-rpi-cm4.dtb
    2021-05-25T17:09:08.7930923Z make[1]: Entering directory '/home/runner/work/photOS/photOS/output/raspberrypi4/build/linux-custom'
    2021-05-25T17:09:09.2954568Z make[2]: *** No rule to make target 'arch/arm/boot/dts/broadcom/bcm2711-rpi-cm4.dtb'.  Stop.
    2021-05-25T17:09:09.2957930Z make[1]: *** [Makefile:1338: broadcom/bcm2711-rpi-cm4.dtb] Error 2

It seems to be related to this commit: https://github.com/ccrisan/thingos/commit/1b69695f1684c7938c0ca6819019fd9fa276ea25

Any hint what I'm missing here?

**Comment by ccrisan** [comment]
This should now be fixed in `dev`.
